# Generated by Django 5.0 on 2023-12-16 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseQuestion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('src', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('question_text', models.TextField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('casestudy', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DragDropOrder',
            fields=[
                ('basequestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PyMB800_app.basequestion')),
                ('items', models.JSONField()),
                ('correct_answer', models.JSONField()),
            ],
            bases=('PyMB800_app.basequestion',),
        ),
        migrations.CreateModel(
            name='DragDropPairs',
            fields=[
                ('basequestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PyMB800_app.basequestion')),
                ('pairs', models.JSONField()),
            ],
            bases=('PyMB800_app.basequestion',),
        ),
        migrations.CreateModel(
            name='DropDown',
            fields=[
                ('basequestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PyMB800_app.basequestion')),
                ('items', models.JSONField()),
                ('correct_answer', models.JSONField()),
            ],
            bases=('PyMB800_app.basequestion',),
        ),
        migrations.CreateModel(
            name='MultipleChoice',
            fields=[
                ('basequestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PyMB800_app.basequestion')),
                ('items', models.JSONField()),
                ('correct_answer', models.JSONField()),
            ],
            bases=('PyMB800_app.basequestion',),
        ),
    ]
